import pool from "../database/keys.js";

const crateTables = async () => {
  try {
    await pool.query(`
            -- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.acciones_marketing
(
    id_accion integer NOT NULL,
    id_clasificacion integer,
    id_redsocial integer,
    descripcion text COLLATE pg_catalog."default",
    fecha_inicio date,
    fecha_fin date,
    CONSTRAINT acciones_marketing_pkey PRIMARY KEY (id_accion)
);

CREATE TABLE IF NOT EXISTS public.clasificacion_usuarios
(
    id_clasificacion integer NOT NULL,
    tipo character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT clasificacion_usuarios_pkey PRIMARY KEY (id_clasificacion)
);

CREATE TABLE IF NOT EXISTS public.clientes
(
    id serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default",
    telefono character varying(20) COLLATE pg_catalog."default",
    direccion character varying(255) COLLATE pg_catalog."default",
    ciudad character varying(100) COLLATE pg_catalog."default",
    pais character varying(100) COLLATE pg_catalog."default",
    pasword character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT clientes_pkey PRIMARY KEY (id),
    CONSTRAINT clientes_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.consultorio_tratamiento
(
    id_consultorio integer NOT NULL,
    id_tratamiento integer NOT NULL,
    id_consultorio_tratamiento integer NOT NULL DEFAULT nextval('consultorio_tratamiento_id_seq'::regclass),
    CONSTRAINT consultorio_tratamiento_pkey PRIMARY KEY (id_consultorio_tratamiento)
);

CREATE TABLE IF NOT EXISTS public.consultorios
(
    id_consultorio serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT consultorios_pkey PRIMARY KEY (id_consultorio)
);

CREATE TABLE IF NOT EXISTS public.imagenes
(
    id_imagenes serial NOT NULL,
    id_visita integer NOT NULL,
    ruta_imagen text COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    CONSTRAINT imagenes_pkey PRIMARY KEY (id_imagenes)
);

CREATE TABLE IF NOT EXISTS public.pacientes
(
    id_paciente serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    apellido character varying(100) COLLATE pg_catalog."default" NOT NULL,
    fecha_nacimiento date,
    genero character(1) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(15) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    direccion character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pacientes_pkey PRIMARY KEY (id_paciente)
);

CREATE TABLE IF NOT EXISTS public.profesional
(
    id integer NOT NULL,
    nombre character varying(65) COLLATE pg_catalog."default",
    numero_matricula character varying(100) COLLATE pg_catalog."default",
    especialidad character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT profesional_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.redes_sociales
(
    id_redsocial integer NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default",
    url character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT redes_sociales_pkey PRIMARY KEY (id_redsocial)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    id serial NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT roles_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.tratamientos
(
    id_tratamiento integer NOT NULL DEFAULT nextval('tratamientos_temp_id_tratamiento_seq'::regclass),
    nombre character varying(100) COLLATE pg_catalog."default",
    descripcion text COLLATE pg_catalog."default",
    duracion integer,
    costo numeric(10, 2),
    color character varying COLLATE pg_catalog."default",
    CONSTRAINT tratamientos_temp_pkey PRIMARY KEY (id_tratamiento)
);

CREATE TABLE IF NOT EXISTS public.turnos
(
    id_paciente integer,
    fecha date,
    hora time without time zone,
    estado character varying(20) COLLATE pg_catalog."default",
    id_turno serial NOT NULL,
    usuario_id integer,
    id_consultorio_tratamiento integer,
    CONSTRAINT turnos_pkey PRIMARY KEY (id_turno)
);

CREATE TABLE IF NOT EXISTS public.turnosfisponibles
(
    turno_id serial NOT NULL,
    fecha date NOT NULL,
    hora time without time zone NOT NULL,
    estado character varying(20) COLLATE pg_catalog."default" DEFAULT 'disponible'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT turnosfisponibles_pkey PRIMARY KEY (turno_id)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password character varying(100) COLLATE pg_catalog."default" NOT NULL,
    rol_id integer,
    creado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    telefono character varying(20) COLLATE pg_catalog."default" NOT NULL,
    direccion character varying(255) COLLATE pg_catalog."default" NOT NULL,
    ciudad character varying(100) COLLATE pg_catalog."default" NOT NULL,
    pais character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT usuarios_pkey PRIMARY KEY (id),
    CONSTRAINT usuarios_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.visitas
(
    id_visita serial NOT NULL,
    id_turno integer NOT NULL,
    id_profesional integer NOT NULL,
    motivo_consulta text COLLATE pg_catalog."default" NOT NULL,
    diagnostico text COLLATE pg_catalog."default",
    observaciones text COLLATE pg_catalog."default",
    CONSTRAINT visitas_pkey PRIMARY KEY (id_visita)
);

ALTER TABLE IF EXISTS public.acciones_marketing
    ADD CONSTRAINT acciones_marketing_id_clasificacion_fkey FOREIGN KEY (id_clasificacion)
    REFERENCES public.clasificacion_usuarios (id_clasificacion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.acciones_marketing
    ADD CONSTRAINT acciones_marketing_id_redsocial_fkey FOREIGN KEY (id_redsocial)
    REFERENCES public.redes_sociales (id_redsocial) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.consultorio_tratamiento
    ADD CONSTRAINT consultorio_tratamiento_id_consultorio_fkey FOREIGN KEY (id_consultorio)
    REFERENCES public.consultorios (id_consultorio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.consultorio_tratamiento
    ADD CONSTRAINT consultorio_tratamiento_id_tratamiento_fkey FOREIGN KEY (id_tratamiento)
    REFERENCES public.tratamientos (id_tratamiento) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.imagenes
    ADD CONSTRAINT fk_visita FOREIGN KEY (id_visita)
    REFERENCES public.visitas (id_visita) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.turnos
    ADD CONSTRAINT turnos_id_consultorio_tratamiento_fkey FOREIGN KEY (id_consultorio_tratamiento)
    REFERENCES public.consultorio_tratamiento (id_consultorio_tratamiento) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.turnos
    ADD CONSTRAINT turnos_id_paciente_fkey FOREIGN KEY (id_paciente)
    REFERENCES public.pacientes (id_paciente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.turnos
    ADD CONSTRAINT turnos_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.usuarios
    ADD CONSTRAINT usuarios_rol_id_fkey FOREIGN KEY (rol_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.visitas
    ADD CONSTRAINT fk_profesional FOREIGN KEY (id_profesional)
    REFERENCES public.profesional (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.visitas
    ADD CONSTRAINT fk_turnos FOREIGN KEY (id_turno)
    REFERENCES public.turnos (id_turno) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

    CREATE TABLE IF NOT EXISTS refresh_tokens (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  token_hash VARCHAR(255) NOT NULL,
  expires_at DATETIME NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  
  -- Índices para búsquedas rápidas
  INDEX idx_user_id (user_id),
  INDEX idx_token_hash (token_hash),
  INDEX idx_expires_at (expires_at),
  
  -- Restricción de clave foránea
  CONSTRAINT fk_refresh_tokens_user
    FOREIGN KEY (user_id) 
    REFERENCES usuarios(id)
    ON DELETE CASCADE
);

-- Índice compuesto para búsquedas por usuario y token hash
CREATE INDEX idx_user_token ON refresh_tokens(user_id, token_hash);

END;
`);

    console.log("✅ Tablas creadas o ya existentes.");
  } catch (error) {
    console.error("Error al crear las tablas:", error);
  } finally {
    await pool.end();
  }
};

createTables();
